package ReverseModule;


/**
* ReverseModule/Reverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Thursday, 3 April, 2025 12:58:42 PM IST
*/

public interface Reverse extends ReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverse
